### ISSUE TITLE
If it's convenient to share the code of training.

### ISSUE THREAD

**Issue by BokaiLIAN** [RyanXingQL/RBQE#2]
Hi Xing,

Thanks for your interesting work, which introduce the very idea of "early stop".  Recently I want to make some changes over your work in a different area, So I wander if it's possible to realse the corresponding training code.
Thanks

Yours,
Lian

**Comment by RyanXingQL** [comment]
Hi Lian, Thank you so much for your interest!

The training for this work is detailed in Sec 4.2. Note that we do not early stop when training. We set the weight of each output loss, so that the whole RBQE network can be trained end-to-end.

The training process is somehow native in my view. We're trying to polish and improve the training process. A better version of training will be released soon. You can also try on this and publish your own work~
Thx~

**Comment by BokaiLIAN** [comment]
Thanks, Looking forward to your lastest version~
